import type { Metadata } from "next";
import { Inter } from "next/font/google";
import GeistMono from "@next/font/local";
import "./globals.css";

import Footer from "./components/footer";
import Navbar from "./components/navbar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = GeistMono({ // Configure GeistMono
  src: [
    {
      path: './fonts/GeistMono-Regular.woff2', // Adjust paths based on your file structure
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/GeistMono-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
    // Add other weights and styles as needed
  ],
  variable: "--font-geist-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by Create Next App",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable} ${geistMono.variable}`}> {/* Apply both font variables */}
      <body className={`antialiased bg-gray-50 text-gray-900 font-geist-mono`}> {/* Use the Geist Mono class */}
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}